[project]
name = "so-hoa-vbcc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Phùng Hùng", email = "hungfungvan@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "openai>=3.24.0",
    "openpyxl>=3.1.5",
    "pandas>=3.0.6",
    "pillow>=12.3.0",
    "pillow-heif>=1.8.0",
    "python-dotenv>=1.2.4",
    "thefuzz>=0.22.1",
]

[project.scripts]
so-hoa-vbcc = "so_hoa_vbcc:main"

[dependency-groups]
dev = [
    "pyinstaller>=6.22.3",
]
